/*
 * build-core.mjs — derive a headless, node-8-compatible sendspin-core.js from
 * the browser bundle sendspin-lib.js.
 *
 * Strategy (see docs/PROGRESS.md, Phase 2 core):
 *   1. Slice the decoder-free "keeper" block out of sendspin-lib.js: the protocol
 *      stack (ProtocolHandler, StateManager, WebSocketManager, SendspinTimeFilter,
 *      MessageType, SendspinPlayer, helpers). Lines 1778..3085 (1-indexed) — verified
 *      to contain no WASM decoder / AudioContext references and exactly one
 *      `new AudioProcessor(...)`.
 *   2. Swap that one `new AudioProcessor(...)` for our headless GstAudioProcessor.
 *   3. Wrap as an ESM entry that imports GstAudioProcessor and re-exports the
 *      public API, then let esbuild transpile `?.`/`??` etc. down to node8.12.
 *
 * Run: node build-core.mjs   (then esbuild step in build.sh)
 */
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");

const KEEP_START = 1778; // first line of the keeper block (const STATE_UPDATE_INTERVAL...)
const KEEP_END = 3085;   // last line of SendspinPlayer's closing brace

const lib = readFileSync(join(repoRoot, "sendspin-lib.js"), "utf8").split("\n");
const block = lib.slice(KEEP_START - 1, KEEP_END).join("\n");

// Anchor checks so a future re-bundle fails loudly if line numbers drift.
if (!/const STATE_UPDATE_INTERVAL = 5000/.test(block)) {
    throw new Error("KEEP_START drifted: STATE_UPDATE_INTERVAL not at block top");
}
if (!/class SendspinPlayer/.test(block)) {
    throw new Error("keeper block missing SendspinPlayer");
}
const apCount = (block.match(/new AudioProcessor\(/g) || []).length;
if (apCount !== 1) {
    throw new Error(`expected exactly 1 'new AudioProcessor(' in block, found ${apCount}`);
}

// Replace the single browser AudioProcessor instantiation with the headless one.
// The original is one long statement ending in `);` on the same line.
const swapped = block.replace(
    /this\.audioProcessor = new AudioProcessor\([^\n]*\);/,
    "this.audioProcessor = new GstAudioProcessor(this.stateManager, this.timeFilter, this.config);"
);
if (swapped === block) {
    throw new Error("AudioProcessor instantiation swap did not match");
}

const header = `/* AUTO-GENERATED by build-core.mjs from sendspin-lib.js. Do not edit by hand. */
import { GstAudioProcessor } from "./gst-audio-processor.mjs";
`;
const footer = `
export { SendspinPlayer, MessageType, SendspinTimeFilter };
`;

writeFileSync(join(here, "src", "sendspin-core.entry.mjs"), header + swapped + footer);
console.log(`[build-core] wrote src/sendspin-core.entry.mjs (${swapped.split("\n").length} keeper lines)`);
